### ISSUE TITLE
Document how to set a custom event to destroy the components on

### ISSUE THREAD

**Issue by connorshea** [jeffreyguenther/vue-turbolinks#27]
From what I've gathered, I think this is how you set it to a custom value?

```javascript
Vue.use(TurbolinksAdapter, { turbolinksDestroyEvent: 'turbolinks:before-cache' })
```

**Comment by excid3** [comment]
Yep that should do it. 

Also just so you know, if you want a more ideal setup, you can have Vue mount to an ID, and then have the same ID on your Vue template's main element. That way you can skip this library for the most part. Vue replaces the element on the page, so if you replace it with one that contains the same ID, it can remount safely and replace the cached HTML that Turbolinks saved.

Since it's easy to miss that, we made this package so it's all taken care of for you automatically but it introduces flicker since we have to remove the Vue's render HTML before cache so it can remount safely next pageview.

**Comment by navinpeiris** [comment]
Hi @excid3 can you please elaborate on what you meant above with an example if you don't mind? Thanks in advance!
